# Generated by Django 4.1.6 on 2023-02-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            (".......", "......."),
                            ("male", "male"),
                            ("female", "female"),
                        ],
                        max_length=20,
                    ),
                ),
                ("password", models.CharField(max_length=20)),
                ("password1", models.CharField(max_length=20)),
            ],
        ),
    ]
